In [1]:
result=[]

for i in range(10):
    result.append(i)
    
print(result)
print()

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]



- List comprehension

In [2]:
result2= [i for i in range(10)]
print(result2)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [3]:
result3 = []

for i in range(10): 
    if i%2 == 0:
        result3.append(i)
        
print(result3)
print()

[0, 2, 4, 6, 8]



In [4]:
result4= [i for i in range(10) if i%2 ==0]
print(result4)

[0, 2, 4, 6, 8]


In [5]:
result5 = []

for i in range(10): 
    if i%2 == 0:
        result5.append(i)
    else:
        result5.append(99)
        
print(result5)
print()

[0, 99, 2, 99, 4, 99, 6, 99, 8, 99]



### 주의

In [6]:
result6= [i if i%2 ==0 else 99  for i in range(10)] 
print(result6)

[0, 99, 2, 99, 4, 99, 6, 99, 8, 99]


In [7]:
result=[]
case1 = ['A','B','C']
case2 = ['A','B','C']
for i in case1:
    for j in case2:
        result.append(i+j)
        
print(result)

['AA', 'AB', 'AC', 'BA', 'BB', 'BC', 'CA', 'CB', 'CC']


In [8]:
result2= [i+j for i in case1 for j in case2]
print (result2)

['AA', 'AB', 'AC', 'BA', 'BB', 'BC', 'CA', 'CB', 'CC']


In [9]:
result3= [i+j for i in case1 for j in case2 if i!=j ]
print (result3)

['AB', 'AC', 'BA', 'BC', 'CA', 'CB']


In [10]:
import numpy as np

In [11]:
a1 = np.array([0,1,2,3,4,5])
print(a1)

[0 1 2 3 4 5]


In [12]:
print (type(a1))

<class 'numpy.ndarray'>


In [13]:
print(a1.dtype)

int32


In [14]:
list1 = [[1,2,3],[4,5,6,],[7,8,9]]
print(list1)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]


In [15]:
list2 = np.array(list1)
print(list2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [16]:
a= np.arange(0,10,2)
print (a)

[0 2 4 6 8]


In [17]:
a= np.arange(10)
print (a)

[0 1 2 3 4 5 6 7 8 9]


In [18]:
a= np.arange(1,10)
print (a)

[1 2 3 4 5 6 7 8 9]


In [19]:
a=np.arange(12).reshape(4,3)
print(a)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [20]:
a=np.arange(1,13).reshape(4,-1)
print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [21]:
a=np.arange(1,13).reshape(-1,3)
print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [22]:
a = np.linspace(1,10,10)
print(a)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [23]:
a = np.linspace(0,np.pi,20)
print(a)

[0.         0.16534698 0.33069396 0.49604095 0.66138793 0.82673491
 0.99208189 1.15742887 1.32277585 1.48812284 1.65346982 1.8188168
 1.98416378 2.14951076 2.31485774 2.48020473 2.64555171 2.81089869
 2.97624567 3.14159265]


In [24]:
	a1 = np.zeros(10, int)
	print(a1)
	a2 = np.zeros((3, 4), int)
	print(a2)
	a3 = np.ones(5)
	print(a3)
	a4 = np.ones((3, 5))
	print(a4)
	a5 = np.eye(3)
print(a5)

[0 0 0 0 0 0 0 0 0 0]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[1. 1. 1. 1. 1.]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [25]:
list1 =[10, 20, 30, 40]
list2 =[1,2,3,4]
print(list1+list2)

[10, 20, 30, 40, 1, 2, 3, 4]


In [27]:
a1 = np.array(list1)
a2 = np.array(list2)
print(a1+a2)

[11 22 33 44]


- element-wise operation

In [28]:
print(a1>a2)

[ True  True  True  True]


In [31]:
a1 = np.arange(1, 6)
    
print(a1.sum())         #전체 합
print(a1.mean())       #평균
print(a1.std())
print(a1.var())
print(a1.min())         #최솟값
print(a1.max())        #최댓값
print(a1.cumsum())  #누적 덧셈
print(a1.cumprod()) #누적 곱셈

15
3.0
1.4142135623730951
2.0
1
5
[ 1  3  6 10 15]
[  1   2   6  24 120]


In [32]:
a = np.array([0, 1, 2, 3]).reshape(2, 2)
print(a)

b = np.array([3, 2, 0, 1]).reshape(2, 2)
print(b)
print('-'*20)
print(a.dot(b)) # 행렬곲
print(np.dot(a, b)) # 행렬곲
print('-'*20)
print(np.transpose(a)) # 전치행렬
print(a.transpose()) # 전치행렬
print(a.T) # 전치행렬
print('-'*20)
print(np.linalg.inv(a)) # 역행렬
print(np.linalg.det(a)) # 행렬식

[[0 1]
 [2 3]]
[[3 2]
 [0 1]]
--------------------
[[0 1]
 [6 7]]
[[0 1]
 [6 7]]
--------------------
[[0 2]
 [1 3]]
[[0 2]
 [1 3]]
[[0 2]
 [1 3]]
--------------------
[[-1.5  0.5]
 [ 1.   0. ]]
-2.0


In [34]:
a = np.array([0, 10, 20, 30, 40, 50])

print(a[[1, 3, 4]])

b = np.arange(10, 100, 10).reshape(3, 3)
print(b)
print(b[0, 2])
b[2, 2] = 97
print(b)
print(b[1])
print('-'*20)
b[1] = np.array([45, 55, 65])
print(b)
b[2] = [75, 85, 95]
print(b)
print('-'*20)
print(b[[0, 2], [0, 1]]) #b의 [0,0] 과 [2,1] 

[10 30 40]
[[10 20 30]
 [40 50 60]
 [70 80 90]]
30
[[10 20 30]
 [40 50 60]
 [70 80 97]]
[40 50 60]
--------------------
[[10 20 30]
 [45 55 65]
 [70 80 97]]
[[10 20 30]
 [45 55 65]
 [75 85 95]]
--------------------
[10 85]


In [35]:
a = np.array([1, 2, 3, 4, 5, 6])
print(a[a > 3])
print(a[(a % 2) == 0])

[4 5 6]
[2 4 6]


In [36]:
a = np.array([0, 10, 20, 30, 40, 50])
print(a[1:4])
print(a[:3])
print(a[2:])
a[2:5] = np.array([25, 35, 45])
print(a)

[10 20 30]
[ 0 10 20]
[20 30 40 50]
[ 0 10 25 35 45 50]


In [37]:
a = np.arange(10, 100, 10).reshape(3, 3)
print(a)
print(a[1:3, 1:3])
print(a[:3, 1:])
print(a[1][0:2])
a[0:2, 1:3] = np.array([[25, 35], [55, 65]])
print(a)

[[10 20 30]
 [40 50 60]
 [70 80 90]]
[[50 60]
 [80 90]]
[[20 30]
 [50 60]
 [80 90]]
[40 50]
[[10 25 35]
 [40 55 65]
 [70 80 90]]
